jobs:
  build_and_deploy_job:
    steps:
    - name: Build And Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: "/" # Adjust this path to the root of your application or where index.html is located
        output_location: "/build" # Adjust this if your build output is different
